name: cherry pick
on:
  workflow_dispatch:
    inputs:
      SHA:
        type: string
run-name: cherry-pick ${{ github.ref_name }} ${{ inputs.SHA }}
jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Apply and push cherry pick
      run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git cherry-pick ${{ inputs.SHA }}
          git push
